name: Demo CI/CD node

on: [push, pull_request]

jobs:
  node16-demo:
    runs-on: ubuntu-20.04
    steps:
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install packages
        run: npm install

      - name: Running test
        run: npm test

      - name: Running linting
        run: npm run lint

      - name: Building
        run: npm run build
