name: Demo CI/CD node

on: [push, pull_request]

jobs:
  node16-demo:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [16, 18]
    steps:
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Echo something
        run: node --version
